services:
  api:
    build: .
    container_name: aedev-api
    ports:
      - "8000:8000"
    environment:
      ENABLE_INDEXING: "1"

      QDRANT_URL: "http://aedev-qdrant:6333"
      QDRANT_COLLECTION: "child_chunks"

      ELASTIC_URL: "http://aedev-elasticsearch:9200"
      ELASTIC_INDEX: "parent_chunks"
      ENABLE_ELASTIC_INDEXING: "1"
      ELASTIC_REFRESH: "1"

      # --- RERANK ---
      BGE_RERANK_MODEL: "BAAI/bge-reranker-v2-m3"
      BGE_RERANK_CACHE_DIR: "/app/data/hf_cache"
      BGE_RERANK_DEVICE: "cpu"          # "cuda" если реально есть GPU
      BGE_RERANK_BATCH: "8"
      BGE_RERANK_MAX_LEN: "512"
      BGE_RERANK_FP16: "0"

      # preload control
      BGE_RERANK_PRELOAD: "1"
      BGE_RERANK_PRELOAD_MODE: "blocking"   # "background" если хочешь быстрый старт API
      BGE_RERANK_WARMUP: "1"

      # HF cache (НЕ пихаем TRANSFORMERS_CACHE)
      HF_HOME: "/app/data/hf_cache"
      HF_HUB_CACHE: "/app/data/hf_cache"
      HF_HUB_DISABLE_TELEMETRY: "1"
      TOKENIZERS_PARALLELISM: "false"

      K_VEC: "3"
      K_LEX: "3"
      RRF_K0: "60"
      PARENT_ALPHA: "0.25"

      PARENT_CHARS: "2500"
      CHILD_CHARS: "300"

      POSTGRES_DSN: "postgresql+psycopg://postgres:postgres@postgres:5432/aedev"

      AE_AUTO_THREADS: "1"
      AE_THREAD_CAP: "8"

      E5_BATCH_SIZE: "64"
      E5_DEVICE: "auto"
      QDRANT_WAIT: "0"
      QDRANT_BATCH: "512"

    volumes:
      - ./app:/app/app
      - ./data:/app/data

    depends_on:
      - postgres
      - qdrant
      - elasticsearch

    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--access-log", "--log-level", "info"]

  postgres:
    image: postgres:15
    container_name: aedev-postgres
    environment:
      POSTGRES_DB: aedev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:latest
    container_name: aedev-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrantdata:/qdrant/storage

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: aedev-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  pgdata:
  qdrantdata:
  esdata:
